server:
  port: 8080

spring:
  application:
    name: customer-service
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customers
    username: shop
    password: 123
    driverClassName: org.postgresql.Driver